Fix XBox shader compilation error
The UIEffect doesn't work correctly on XBox because the compiler doesn't like that cast. The error is:

Shader error in 'Hidden/UI/Default (UIEffect)': Program 'frag', error: llvm::cast<X>() argument of incompatible type! (on gamecore_scarlett)